[package]
name = "omni"
version = "0.0.0-git"
authors = ["Raphaël Beamonte"]
description = "Omnipotent dev tool"
homepage = "https://github.com/XaF/omni"
edition = "2021"

[build-dependencies]
time = { version = "0.3.22", features = ["serde-well-known"] }

[dependencies]
atty = "0.2.14"
blake3 = "1.4.0"
duct = "0.13.6"
fs4 = "0.6.5"
getopts = "0.2.21"
git-url-parse = "0.4.4"
git2 = "0.17.2"
imara-diff = "0.1.5"
indicatif = "0.17.5"
itertools = "0.10.5"
lazy_static = "1.4.0"
libz-sys = { version = "1.1.9", features = ["static"] }
once_cell = "1.18.0"
openssl = { version = "0.10", features = ["vendored"] }
path-clean = "1.0.1"
pathdiff = "0.2.1"
regex = "1.8.3"
requestty = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.99"
serde_yaml = "0.8"
shell-escape = "0.1.5"
shell-words = "1.1.0"
strsim = "0.10.0"
term_size = "0.3.2"
time = { version = "0.3.22", features = ["serde-well-known"] }
tokio = { version = "1.28.2", features = ["full"] }
url = "2.4.0"
uuid = { version = "1.3.4", features = ["v4", "fast-rng"] }
walkdir = "2.3.3"
