[package]
name = "omni"
version = "0.0.0-git"
authors = ["Raphaël Beamonte"]
description = "Omnipotent dev tool"
homepage = "https://github.com/XaF/omni"
edition = "2021"

[build-dependencies]
time = { version = "0.3.22", features = ["serde-well-known"] }

[dependencies]
blake3 = "1.4.1"
duct = "0.13.6"
flate2 = "1.0.26"
fs4 = "0.6.6"
getopts = "0.2.21"
git-url-parse = "0.4.4"
git2 = "0.17.2"
imara-diff = "0.1.5"
indicatif = "0.17.5"
is-terminal = "0.4.9"
itertools = "0.11.0"
lazy_static = "1.4.0"
libz-sys = { version = "1.1.9", features = ["static"] }
once_cell = "1.18.0"
openssl = { version = "0.10", features = ["vendored"] }
path-clean = "1.0.1"
pathdiff = "0.2.1"
regex = "1.9.0"
requestty = "0.5.0"
reqwest = { version = "0.11.18", features = ["blocking"] }
self-replace = "1.3.5"
semver = "1.0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.100"
serde_yaml = "0.9"
sha2 = "0.10.7"
shell-escape = "0.1.5"
shell-words = "1.1.0"
strsim = "0.10.0"
tar = "0.4.38"
tempfile = "3.6.0"
term_size = "0.3.2"
time = { version = "0.3.22", features = ["serde-well-known"] }
tokio = { version = "1.29.1", features = ["full"] }
url = "2.4.0"
uuid = { version = "1.4.0", features = ["v4", "fast-rng"] }
walkdir = "2.3.3"
