[package]
name = "omnicli"
version = "0.0.0-git"
authors = ["Raphaël Beamonte <raphael.beamonte@gmail.com>"]
description = "Omnipotent dev tool"
documentation = "https://omnicli.dev"
edition = "2021"
homepage = "https://omnicli.dev"
license = "LGPL-2.1"
readme = "README.md"
repository = "https://github.com/XaF/omni"
exclude = [
    ".github/*",
    "website/*",
]

[[bin]]
name = "omni"
path = "src/main.rs"

[build-dependencies]
time = { version = "0.3.30", features = ["serde-well-known"] }

[dependencies]
blake3 = "1.5.0"
clap = "4.4.10"
duct = "0.13.6"
flate2 = "1.0.28"
fs4 = "0.7.0"
gethostname = "0.4.3"
git-url-parse = "0.4.4"
git2 = "0.18.1"
imara-diff = "0.1.5"
indicatif = "0.17.7"
is-terminal = "0.4.9"
itertools = "0.12.0"
lazy_static = "1.4.0"
libz-sys = { version = "1.1.12", features = ["static"] }
machine-uid = "0.5.1"
node-semver = "2.1.0"
once_cell = "1.18.0"
openssl = { version = "0.10", features = ["vendored"] }
package-json = "0.4.0"
path-clean = "1.0.1"
pathdiff = "0.2.1"
petname = "1.1.3"
regex = "1.10.2"
requestty = "0.5.0"
reqwest = { version = "0.11.22", features = ["blocking"] }
self-replace = "1.3.7"
semver = "1.0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9"
sha2 = "0.10.8"
shell-escape = "0.1.5"
shell-words = "1.1.0"
strsim = "0.10.0"
tar = "0.4.40"
tempfile = "3.8.1"
tera = "1.19.1"
term_cursor = "0.2.1"
term_size = "0.3.2"
time = { version = "0.3.30", features = ["serde-well-known"] }
tokio = { version = "1.34.0", features = ["full"] }
url = "2.5.0"
uuid = { version = "1.6.1", features = ["v4", "fast-rng"] }
walkdir = "2.4.0"
