use serde::Deserialize;
// Note: Serialize is auto-generated by compote::Config derive macro

use crate::internal::config::parser::MatchSkipPromptIfConfig;

// ============================================================================
// NEW IMPLEMENTATION USING COMPOTE
// ============================================================================

/// CdConfig using compote's derive macro.
///
/// The compote::Config derive macro automatically generates:
/// - `FromConfigValue` implementation for deserialization from compote's Config
/// - `serde::Serialize` implementation for serialization
///
/// We still need manual `serde::Deserialize` for compatibility with the existing
/// codebase that uses serde for some operations.
#[derive(Debug, Clone, compote::Config)]
pub struct CdConfig {
    #[compote(default = "true")]
    pub fast_search: bool,

    #[compote(default = "0.12")]
    pub path_match_min_score: f64,

    #[compote(nested)]
    pub path_match_skip_prompt_if: MatchSkipPromptIfConfig,
}

// Note: serde::Serialize is auto-generated by compote::Config derive macro

// Manual Deserialize implementation for compatibility with existing code
// (e.g., loading from cache files, etc.)
impl<'de> Deserialize<'de> for CdConfig {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct Helper {
            #[serde(default = "default_fast_search")]
            fast_search: bool,
            #[serde(default = "default_path_match_min_score")]
            path_match_min_score: f64,
            #[serde(default)]
            path_match_skip_prompt_if: MatchSkipPromptIfConfig,
        }

        fn default_fast_search() -> bool { true }
        fn default_path_match_min_score() -> f64 { 0.12 }

        let helper = Helper::deserialize(deserializer)?;
        Ok(CdConfig {
            fast_search: helper.fast_search,
            path_match_min_score: helper.path_match_min_score,
            path_match_skip_prompt_if: helper.path_match_skip_prompt_if,
        })
    }
}

impl Default for CdConfig {
    fn default() -> Self {
        Self {
            fast_search: true,
            path_match_min_score: 0.12,
            path_match_skip_prompt_if: MatchSkipPromptIfConfig::default(),
        }
    }
}
