use serde::Deserialize;
// Note: Serialize is auto-generated by compote::Config derive macro

/// CloneConfig using compote's derive macro.
///
/// The compote::Config derive macro automatically generates:
/// - `FromConfigValue` implementation for deserialization from compote's Config
/// - `serde::Serialize` implementation for serialization
///
/// We still need manual `serde::Deserialize` for compatibility with the existing
/// codebase that uses serde for some operations (e.g., cache files).
#[derive(Debug, Clone, compote::Config)]
pub struct CloneConfig {
    #[compote(default = "true")]
    pub auto_up: bool,

    #[compote(default = "5")]
    pub ls_remote_timeout: u64,
}

// Note: serde::Serialize is auto-generated by compote::Config derive macro

// Manual Deserialize implementation for compatibility with existing code
// (e.g., loading from cache files, etc.)
impl<'de> Deserialize<'de> for CloneConfig {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct Helper {
            #[serde(default = "default_auto_up")]
            auto_up: bool,
            #[serde(default = "default_ls_remote_timeout")]
            ls_remote_timeout: u64,
        }

        fn default_auto_up() -> bool { true }
        fn default_ls_remote_timeout() -> u64 { 5 }

        let helper = Helper::deserialize(deserializer)?;
        Ok(CloneConfig {
            auto_up: helper.auto_up,
            ls_remote_timeout: helper.ls_remote_timeout,
        })
    }
}

impl Default for CloneConfig {
    fn default() -> Self {
        Self {
            auto_up: true,
            ls_remote_timeout: 5,
        }
    }
}
