use serde::Deserialize;
// Note: Serialize is auto-generated by compote::Config derive macro

/// MakefileCommandsConfig using compote's derive macro.
///
/// The compote::Config derive macro automatically generates:
/// - `FromConfigValue` implementation for deserialization from compote's Config
/// - `serde::Serialize` implementation for serialization
///
/// We still need manual `serde::Deserialize` for compatibility with the existing
/// codebase that uses serde for some operations (e.g., loading from cache files).
#[derive(Debug, Clone, compote::Config)]
pub struct MakefileCommandsConfig {
    #[compote(default = "true")]
    pub enabled: bool,

    #[compote(default = "true")]
    pub split_on_dash: bool,

    #[compote(default = "true")]
    pub split_on_slash: bool,
}

impl Default for MakefileCommandsConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            split_on_dash: true,
            split_on_slash: true,
        }
    }
}

// Note: serde::Serialize is auto-generated by compote::Config derive macro

// Manual Deserialize implementation for compatibility with existing code
// (e.g., loading from cache files, etc.)
impl<'de> Deserialize<'de> for MakefileCommandsConfig {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct Helper {
            #[serde(default = "default_enabled")]
            enabled: bool,
            #[serde(default = "default_split_on_dash")]
            split_on_dash: bool,
            #[serde(default = "default_split_on_slash")]
            split_on_slash: bool,
        }

        fn default_enabled() -> bool { true }
        fn default_split_on_dash() -> bool { true }
        fn default_split_on_slash() -> bool { true }

        let helper = Helper::deserialize(deserializer)?;
        Ok(MakefileCommandsConfig {
            enabled: helper.enabled,
            split_on_dash: helper.split_on_dash,
            split_on_slash: helper.split_on_slash,
        })
    }
}
