use std::collections::HashMap;
use std::fmt;
use std::path::PathBuf;

use serde::Deserialize;
// Note: Serialize is auto-generated by compote::Config derive macro

use crate::internal::config::config_value::ConfigData;
use crate::internal::config::parser::errors::ConfigErrorHandler;
use crate::internal::config::parser::errors::ConfigErrorKind;
use crate::internal::config::ConfigScope;
use crate::internal::config::ConfigSource;
use crate::internal::config::ConfigValue;
use crate::internal::git::package_path_from_handle;
use crate::internal::git::package_root_path;

// ============================================================================
// NEW IMPLEMENTATION USING COMPOTE
// ============================================================================

/// PathConfig using compote's derive macro.
///
/// The compote::Config derive macro automatically generates:
/// - `FromConfigValue` implementation for deserialization from compote's Config
/// - `serde::Serialize` implementation for serialization
///
/// We still need manual `serde::Deserialize` for compatibility with the existing
/// codebase that uses serde for some operations.
#[derive(Debug, Clone, compote::Config)]
pub struct PathConfig {
    #[compote(default = "Vec::new()", skip_if_empty)]
    pub append: Vec<PathEntryConfig>,

    #[compote(default = "Vec::new()", skip_if_empty)]
    pub prepend: Vec<PathEntryConfig>,
}


// Manual Deserialize implementation for compatibility with existing code
// (e.g., loading from cache files, etc.)
impl<'de> Deserialize<'de> for PathConfig {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct Helper {
            #[serde(default)]
            append: Vec<PathEntryConfig>,
            #[serde(default)]
            prepend: Vec<PathEntryConfig>,
        }

        let helper = Helper::deserialize(deserializer)?;
        Ok(PathConfig {
            append: helper.append,
            prepend: helper.prepend,
        })
    }
}

impl Default for PathConfig {
    fn default() -> Self {
        Self {
            append: Vec::new(),
            prepend: Vec::new(),
        }
    }
}

/// PathEntryConfig using compote's derive macro.
///
/// The compote::Config derive macro automatically generates:
/// - `FromConfigValue` implementation for deserialization from compote's Config
/// - `serde::Serialize` implementation for serialization
///
/// We still need manual `serde::Deserialize` for compatibility with the existing
/// codebase that uses serde for some operations.
///
/// Note: The `full_path` field is computed and uses `#[compote(skip)]` to exclude
/// it from both serialization and deserialization.
#[derive(Debug, Clone, PartialEq, compote::Config)]
pub struct PathEntryConfig {
    #[compote(default = "String::new()")]
    pub path: String,

    #[compote(skip_if_empty)]
    pub package: Option<String>,

    #[compote(skip, default = "String::new()")]
    pub full_path: String,
}

impl fmt::Display for PathEntryConfig {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.full_path)
    }
}

impl PathEntryConfig {
    pub fn from_path(path: &str) -> Self {
        Self {
            path: path.to_string(),
            package: None,
            full_path: if path.starts_with('/') {
                path.to_string()
            } else {
                "".to_string()
            },
        }
    }

    pub fn from_config_value(
        config_value: &ConfigValue,
        error_handler: &ConfigErrorHandler,
    ) -> Option<Self> {
        if config_value.is_table() {
            let path =
                config_value.get_as_str_or_default("path", "", &error_handler.with_key("path"));
            let package =
                config_value.get_as_str_or_none("package", &error_handler.with_key("package"));
            let absolute_path = path.starts_with('/');

            if let Some(package) = package {
                if absolute_path {
                    error_handler
                        .with_key("package")
                        .with_actual(config_value.get("package").expect("package should exist"))
                        .error(ConfigErrorKind::UnsupportedValueInContext)
                } else if let Some(package_path) = package_path_from_handle(&package) {
                    let mut full_path = package_path;
                    if !path.is_empty() {
                        full_path = full_path.join(path.clone());
                    }

                    return Some(Self {
                        path: path.clone(),
                        package: Some(package.to_string()),
                        full_path: full_path.to_str().unwrap().to_string(),
                    });
                } else {
                    error_handler
                        .with_key("package")
                        .with_context("package", package)
                        .error(ConfigErrorKind::InvalidPackage);

                    return None;
                }
            }

            Some(Self {
                path: path.clone(),
                package: None,
                full_path: path,
            })
        } else if let Some(path) = config_value.as_str_forced() {
            Some(Self {
                path: path.clone(),
                package: None,
                full_path: path,
            })
        } else {
            error_handler
                .with_expected(vec!["string", "table"])
                .with_actual(config_value)
                .error(ConfigErrorKind::InvalidValueType);

            None
        }
    }

    pub fn as_config_value(&self) -> ConfigValue {
        if let Some(package) = &self.package {
            let mut map = HashMap::new();
            map.insert(
                "path".to_string(),
                ConfigValue::from_str_with(ConfigSource::Null, ConfigScope::Null, &self.path).expect("path should be a string"),
            );
            map.insert(
                "package".to_string(),
                ConfigValue::from_str_with(ConfigSource::Null, ConfigScope::Null, package).expect("package should be a string"),
            );
            ConfigValue::new(
                ConfigSource::Null,
                ConfigScope::Null,
                Some(Box::new(ConfigData::Mapping(map))),
            )
        } else {
            ConfigValue::from_str_with(ConfigSource::Null, ConfigScope::Null, &self.full_path).expect("full_path should be a string")
        }
    }

    pub fn is_package(&self) -> bool {
        self.package.is_some() || PathBuf::from(&self.full_path).starts_with(package_root_path())
    }

    pub fn package_path(&self) -> Option<PathBuf> {
        if let Some(package) = &self.package {
            return package_path_from_handle(package);
        }

        None
    }

    pub fn is_valid(&self) -> bool {
        !self.full_path.is_empty() && self.full_path.starts_with('/')
    }

    pub fn starts_with(&self, path_entry: &PathEntryConfig) -> bool {
        if !self.is_valid() {
            return false;
        }

        PathBuf::from(&self.full_path).starts_with(&path_entry.full_path)
    }

    pub fn starts_with_path(&self, path: PathBuf) -> bool {
        if !self.is_valid() {
            return false;
        }

        PathBuf::from(&self.full_path).starts_with(path)
    }

    pub fn includes_path(&self, path: PathBuf) -> bool {
        if !self.is_valid() {
            return false;
        }

        PathBuf::from(&path).starts_with(&self.full_path)
    }

    pub fn replace(&mut self, path_from: &PathEntryConfig, path_to: &PathEntryConfig) -> bool {
        if self.starts_with(path_from) {
            let new_full_path = format!(
                "{}/{}",
                path_to.full_path,
                PathBuf::from(&self.full_path)
                    .strip_prefix(&path_from.full_path)
                    .unwrap()
                    .display(),
            );
            if let Some(package) = path_to.package.clone() {
                if let Some(package_path) = package_path_from_handle(&package) {
                    self.full_path = new_full_path;
                    self.package = Some(package);
                    self.path = PathBuf::from(&self.full_path)
                        .strip_prefix(&package_path)
                        .unwrap()
                        .display()
                        .to_string();

                    return true;
                }
            } else {
                self.full_path = new_full_path;
                self.package = None;
                self.path.clone_from(&self.full_path);

                return true;
            }
        }
        false
    }

    /// Convert to compote Value for use with compote's Config API
    pub fn to_compote_value(&self) -> compote::Value {
        if let Some(package) = &self.package {
            let mut map = indexmap::IndexMap::new();
            map.insert(
                "path".to_string(),
                compote::ConfigValue::string(
                    self.path.clone(),
                    compote::ConfigContext::new(
                        compote::ConfigSource::Programmatic,
                        compote::ConfigLevel::User,
                    ),
                ),
            );
            map.insert(
                "package".to_string(),
                compote::ConfigValue::string(
                    package.clone(),
                    compote::ConfigContext::new(
                        compote::ConfigSource::Programmatic,
                        compote::ConfigLevel::User,
                    ),
                ),
            );
            compote::Value::Object(map)
        } else {
            // Just the path as a string
            compote::Value::String(self.full_path.clone())
        }
    }

    /// Convert from compote ConfigValue to PathEntryConfig
    pub fn from_compote_value(
        config_value: &compote::ConfigValue,
        error_handler: &ConfigErrorHandler,
    ) -> Option<Self> {
        match &config_value.value {
            compote::Value::Object(map) => {
                let path = map
                    .get("path")
                    .and_then(|v| match &v.value {
                        compote::Value::String(s) => Some(s.clone()),
                        _ => None,
                    })
                    .unwrap_or_default();

                let package = map.get("package").and_then(|v| match &v.value {
                    compote::Value::String(s) => Some(s.clone()),
                    _ => None,
                });

                let absolute_path = path.starts_with('/');

                if let Some(package) = package {
                    if absolute_path {
                        error_handler
                            .with_key("package")
                            .error(ConfigErrorKind::UnsupportedValueInContext);
                        None
                    } else if let Some(package_path) = package_path_from_handle(&package) {
                        let mut full_path = package_path;
                        if !path.is_empty() {
                            full_path = full_path.join(path.clone());
                        }

                        Some(Self {
                            path: path.clone(),
                            package: Some(package.to_string()),
                            full_path: full_path.to_str().unwrap().to_string(),
                        })
                    } else {
                        error_handler
                            .with_key("package")
                            .with_context("package", package)
                            .error(ConfigErrorKind::InvalidPackage);
                        None
                    }
                } else {
                    Some(Self {
                        path: path.clone(),
                        package: None,
                        full_path: path,
                    })
                }
            }
            compote::Value::String(path) => Some(Self {
                path: path.clone(),
                package: None,
                full_path: path.clone(),
            }),
            compote::Value::Int(i) => Some(Self {
                path: i.to_string(),
                package: None,
                full_path: i.to_string(),
            }),
            _ => {
                error_handler
                    .with_expected(vec!["string", "object"])
                    .error(ConfigErrorKind::InvalidValueType);
                None
            }
        }
    }
}

// Manual Deserialize implementation for compatibility with existing code
// (e.g., loading from cache files, etc.)
impl<'de> Deserialize<'de> for PathEntryConfig {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct Helper {
            #[serde(default)]
            path: String,
            #[serde(default)]
            package: Option<String>,
            // Note: full_path is skipped in deserialization
        }

        let helper = Helper::deserialize(deserializer)?;
        Ok(PathEntryConfig {
            path: helper.path.clone(),
            package: helper.package,
            // Compute full_path from path (matching the from_path behavior)
            full_path: if helper.path.starts_with('/') {
                helper.path
            } else {
                String::new()
            },
        })
    }
}

impl Default for PathEntryConfig {
    fn default() -> Self {
        Self {
            path: String::new(),
            package: None,
            full_path: String::new(),
        }
    }
}
