use std::collections::HashMap;

use crate::internal::config::utils::check_allowed;

// ============================================================================
// NEW IMPLEMENTATION USING COMPOTE
// ============================================================================

/// UpCommandConfig using compote's derive macro.
///
/// The compote::Config derive macro automatically generates:
/// - `FromConfigValue` implementation for deserialization from compote's Config
/// - `serde::Serialize` implementation for serialization
///
/// We still need manual `serde::Deserialize` for compatibility with the existing
/// codebase that uses serde for some operations.
///
/// Field mutability notes:
/// - Fields with `mutable_by = ["system", "user"]` cannot be overridden by workdir:
///   - auto_bootstrap
///   - notify_workdir_config_updated
///   - notify_workdir_config_available
///   - preferred_tools
///   - mise_version
///   - uv_version
/// - Fields without mutable_by (workdir can override):
///   - attach_kill_timeout (duration)
///   - attach_lock_timeout (duration)
///   - upgrade
///   - operations (nested struct)
#[derive(Debug, Clone, compote::Config)]
pub struct UpCommandConfig {
    #[compote(default = "true", mutable_by = ["system", "user"])]
    pub auto_bootstrap: bool,

    #[compote(default = "true", mutable_by = ["system", "user"])]
    pub notify_workdir_config_updated: bool,

    #[compote(default = "true", mutable_by = ["system", "user"])]
    pub notify_workdir_config_available: bool,

    #[compote(duration, default = "600")]
    pub attach_kill_timeout: u64,

    #[compote(duration, default = "5")]
    pub attach_lock_timeout: u64,

    #[compote(default = "Vec::new()", skip_if_empty, mutable_by = ["system", "user"])]
    pub preferred_tools: Vec<String>,

    #[compote(default = "latest", mutable_by = ["system", "user"])]
    pub mise_version: String,

    #[compote(default = "latest", mutable_by = ["system", "user"])]
    pub uv_version: String,

    #[compote(default = "false")]
    pub upgrade: bool,

    #[compote(default, serde_skip_serializing_if = "UpCommandOperationConfig::is_empty")]
    pub operations: UpCommandOperationConfig,
}

impl Default for UpCommandConfig {
    fn default() -> Self {
        Self {
            attach_kill_timeout: 600, // 10 minutes
            attach_lock_timeout: 5,   // 5 seconds
            auto_bootstrap: true,
            mise_version: "latest".to_string(),
            uv_version: "latest".to_string(),
            notify_workdir_config_updated: true,
            notify_workdir_config_available: true,
            operations: UpCommandOperationConfig::default(),
            preferred_tools: Vec::new(),
            upgrade: false,
        }
    }
}

// Note: serde::Serialize and serde::Deserialize are auto-generated by compote::Config derive macro

/// UpCommandOperationConfig using compote's derive macro.
///
/// All fields are restricted to system and user levels only (mutable_by = ["system", "user"]).
#[derive(Debug, Clone, compote::Config)]
#[compote(mutable_by = ["system", "user"])]
pub(crate) struct UpCommandOperationConfig {
    #[compote(default = "Vec::new()", skip_if_empty)]
    pub allowed: Vec<String>,

    #[compote(default = "Vec::new()", skip_if_empty)]
    pub sources: Vec<String>,

    #[compote(default, serde_skip_serializing_if = "UpCommandOperationMiseConfig::is_empty")]
    pub mise: UpCommandOperationMiseConfig,

    #[compote(
        rename = "cargo-install",
        default,
        serde_skip_serializing_if = "UpCommandOperationCargoInstallConfig::is_empty"
    )]
    pub cargo_install: UpCommandOperationCargoInstallConfig,

    #[compote(
        rename = "go-install",
        default,
        serde_skip_serializing_if = "UpCommandOperationGoInstallConfig::is_empty"
    )]
    pub go_install: UpCommandOperationGoInstallConfig,

    #[compote(
        rename = "github-release",
        default,
        serde_skip_serializing_if = "UpCommandOperationGithubReleaseConfig::is_empty"
    )]
    pub github_release: UpCommandOperationGithubReleaseConfig,
}

impl Default for UpCommandOperationConfig {
    fn default() -> Self {
        Self {
            allowed: Vec::new(),
            sources: Vec::new(),
            mise: UpCommandOperationMiseConfig::default(),
            cargo_install: UpCommandOperationCargoInstallConfig::default(),
            go_install: UpCommandOperationGoInstallConfig::default(),
            github_release: UpCommandOperationGithubReleaseConfig::default(),
        }
    }
}

impl UpCommandOperationConfig {
    /// Check if this config is empty (used by serde skip_serializing_if)
    #[allow(dead_code)]
    pub(crate) fn is_empty(&self) -> bool {
        self.allowed.is_empty() && self.sources.is_empty()
    }

    pub fn is_operation_allowed(&self, operation: &str) -> bool {
        check_allowed(operation, &self.allowed)
    }

    pub fn is_mise_backend_allowed(&self, backend: &str) -> bool {
        check_allowed(backend, &self.mise.backends)
    }

    pub fn is_mise_source_allowed(&self, source: &str) -> bool {
        check_url_allowed(source, &self.sources) && check_url_allowed(source, &self.mise.sources)
    }

    pub fn is_go_install_source_allowed(&self, source: &str) -> bool {
        let source = format!("https://{}", source.trim_start_matches("https://"));
        check_url_allowed(&source, &self.sources)
            && check_url_allowed(&source, &self.go_install.sources)
    }

    pub fn is_cargo_install_crate_allowed(&self, crate_name: &str) -> bool {
        check_allowed(crate_name, &self.cargo_install.crates)
    }

    pub fn is_github_repository_allowed(&self, repository: &str) -> bool {
        let url_from_repository = format!("https://github.com/{repository}");
        check_url_allowed(&url_from_repository, &self.sources)
            && check_allowed(repository, &self.github_release.repositories)
    }
}


/// UpCommandOperationMiseConfig using compote's derive macro.
///
/// All fields are restricted to system and user levels only (mutable_by = ["system", "user"]).
/// Contains HashMap<String, String> for default_plugin_sources which is now supported by compote.
#[derive(Debug, Clone, compote::Config)]
#[compote(mutable_by = ["system", "user"])]
pub(crate) struct UpCommandOperationMiseConfig {
    #[compote(default = "Vec::new()", skip_if_empty)]
    pub backends: Vec<String>,

    #[compote(default = "Vec::new()", skip_if_empty)]
    pub sources: Vec<String>,

    #[compote(default = "HashMap::new()", serde_skip_serializing_if = "HashMap::is_empty")]
    pub default_plugin_sources: HashMap<String, String>,
}

impl Default for UpCommandOperationMiseConfig {
    fn default() -> Self {
        Self {
            backends: Vec::new(),
            sources: Vec::new(),
            default_plugin_sources: HashMap::new(),
        }
    }
}

impl UpCommandOperationMiseConfig {
    /// Check if this config is empty (used by serde skip_serializing_if)
    #[allow(dead_code)]
    pub(crate) fn is_empty(&self) -> bool {
        self.backends.is_empty()
            && self.sources.is_empty()
            && self.default_plugin_sources.is_empty()
    }
}


/// UpCommandOperationCargoInstallConfig using compote's derive macro.
///
/// All fields are restricted to system and user levels only (mutable_by = ["system", "user"]).
#[derive(Debug, Clone, compote::Config)]
#[compote(mutable_by = ["system", "user"])]
pub(crate) struct UpCommandOperationCargoInstallConfig {
    #[compote(default = "Vec::new()", skip_if_empty)]
    pub crates: Vec<String>,
}

impl Default for UpCommandOperationCargoInstallConfig {
    fn default() -> Self {
        Self { crates: Vec::new() }
    }
}

impl UpCommandOperationCargoInstallConfig {
    /// Check if this config is empty (used by serde skip_serializing_if)
    #[allow(dead_code)]
    pub(crate) fn is_empty(&self) -> bool {
        self.crates.is_empty()
    }
}


/// UpCommandOperationGoInstallConfig using compote's derive macro.
///
/// All fields are restricted to system and user levels only (mutable_by = ["system", "user"]).
#[derive(Debug, Clone, compote::Config)]
#[compote(mutable_by = ["system", "user"])]
pub struct UpCommandOperationGoInstallConfig {
    #[compote(default = "Vec::new()", skip_if_empty)]
    pub sources: Vec<String>,
}

impl Default for UpCommandOperationGoInstallConfig {
    fn default() -> Self {
        Self {
            sources: Vec::new(),
        }
    }
}

impl UpCommandOperationGoInstallConfig {
    /// Check if this config is empty (used by serde skip_serializing_if)
    #[allow(dead_code)]
    pub(crate) fn is_empty(&self) -> bool {
        self.sources.is_empty()
    }
}


/// UpCommandOperationGithubReleaseConfig using compote's derive macro.
///
/// All fields are restricted to system and user levels only (mutable_by = ["system", "user"]).
#[derive(Debug, Clone, compote::Config)]
#[compote(mutable_by = ["system", "user"])]
pub struct UpCommandOperationGithubReleaseConfig {
    #[compote(default = "Vec::new()", skip_if_empty)]
    pub repositories: Vec<String>,
}

impl Default for UpCommandOperationGithubReleaseConfig {
    fn default() -> Self {
        Self {
            repositories: Vec::new(),
        }
    }
}

impl UpCommandOperationGithubReleaseConfig {
    /// Check if this config is empty (used by serde skip_serializing_if)
    #[allow(dead_code)]
    pub(crate) fn is_empty(&self) -> bool {
        self.repositories.is_empty()
    }
}


// ============================================================================
// URL Pattern Matching (unchanged from original)
// ============================================================================

#[derive(Debug, Clone)]
struct UrlPattern {
    scheme: Option<String>,
    host: Option<String>,
    port: Option<String>,
    username: Option<String>,
    password: Option<String>,
    path: Option<String>,
    query: Option<String>,
    fragment: Option<String>,
}

impl UrlPattern {
    fn parse(url_str: &str) -> Result<Self, url::ParseError> {
        match url::Url::parse(url_str) {
            Ok(url) if url.host_str().is_none() || url.cannot_be_a_base() => {
                let prefixed_url = format!("https://{url_str}");
                match Self::parse(&prefixed_url) {
                    Ok(mut url) => {
                        url.scheme = None;
                        Ok(url)
                    }
                    Err(err) => Err(err),
                }
            }
            Ok(url) => Ok(url.into()),
            Err(url::ParseError::RelativeUrlWithoutBase) => {
                let prefixed_url = format!("https://{url_str}");
                match Self::parse(&prefixed_url) {
                    Ok(mut url) => {
                        url.scheme = None;
                        Ok(url)
                    }
                    Err(err) => Err(err),
                }
            }
            Err(url::ParseError::InvalidPort) => {
                let (cleared_url, port) = Self::_remove_url_port(url_str);
                let port = match port {
                    Some(port) => port,
                    None => return Err(url::ParseError::InvalidPort),
                };

                match Self::parse(&cleared_url) {
                    Ok(mut url) => {
                        url.port = Some(port);
                        Ok(url)
                    }
                    Err(err) => Err(err),
                }
            }
            Err(err) => Err(err),
        }
    }

    /// This identifies if there is a port specified in the URL and
    /// removes it if it's the case, this supports any port even if
    /// it would be considered as an invalid port, which allows to
    /// handle glob patterns
    fn _remove_url_port(url: &str) -> (String, Option<String>) {
        // (A) Find scheme end
        let after_scheme = url.find("://").map(|pos| pos + 3).unwrap_or(0);

        // (B) Find path start
        let path_start = url[after_scheme..]
            .find('/')
            .map(|pos| pos + after_scheme)
            .unwrap_or(url.len());

        // (C) Find auth end
        let auth_end = url[after_scheme..path_start]
            .find('@')
            .map(|pos| pos + after_scheme)
            .unwrap_or(0);

        // (D) Find last colon before path
        if let Some(colon_pos) = url[auth_end..path_start].rfind(':') {
            let port_start = auth_end + colon_pos;
            let port_end = path_start;

            let port = url[port_start + 1..port_end].to_string();
            if !port.is_empty() {
                let url = url[..port_start].to_string() + &url[port_end..];
                return (url, Some(port));
            }
        }

        (url.to_string(), None)
    }

    fn matches(&self, other_url: &UrlPattern) -> bool {
        for param in &[
            (self.scheme.as_deref(), other_url.scheme.as_deref()),
            (self.host.as_deref(), other_url.host.as_deref()),
            (self.port.as_deref(), other_url.port.as_deref()),
            (self.username.as_deref(), other_url.username.as_deref()),
            (self.password.as_deref(), other_url.password.as_deref()),
            (self.path.as_deref(), other_url.path.as_deref()),
            (self.query.as_deref(), other_url.query.as_deref()),
            (self.fragment.as_deref(), other_url.fragment.as_deref()),
        ] {
            let (pattern, component) = param;
            if !Self::_matches_pattern(*component, *pattern) {
                return false;
            }
        }
        true
    }

    fn _matches_pattern(component: Option<&str>, pattern: Option<&str>) -> bool {
        match (component, pattern) {
            (_, None) => true,
            (c, Some(p)) => glob::Pattern::new(p).is_ok_and(|pat| pat.matches(c.unwrap_or(""))),
        }
    }
}

impl From<url::Url> for UrlPattern {
    fn from(url: url::Url) -> Self {
        Self {
            scheme: match url.scheme() {
                "" => None,
                scheme => Some(scheme.to_string()),
            },
            host: url.host_str().map(|h| h.to_string()),
            port: url.port().map(|p| p.to_string()),
            username: match url.username() {
                "" => None,
                username => Some(username.to_string()),
            },
            password: url.password().map(|p| p.to_string()),
            path: match url.path().strip_prefix('/').unwrap_or(url.path()) {
                "" => None,
                path => Some(path.to_string()),
            },
            query: url.query().map(|q| q.to_string()),
            fragment: url.fragment().map(|f| f.to_string()),
        }
    }
}

fn check_url_allowed(url_str: &str, patterns: &[String]) -> bool {
    if patterns.is_empty() {
        return true; // No patterns means allow all
    }

    let url = match UrlPattern::parse(url_str) {
        Ok(url) => url,
        Err(_) => return false, // Invalid URL
    };

    for pattern in patterns {
        let is_deny = pattern.starts_with('!');
        let pattern_str = if is_deny { &pattern[1..] } else { pattern };

        let pattern_url = match UrlPattern::parse(pattern_str) {
            Ok(url) => url,
            Err(_err) => continue, // Skip invalid patterns
        };

        let matches = pattern_url.matches(&url);
        if matches {
            return !is_deny; // Early return on match
        }
    }

    // Get the last pattern's deny status (if any) for the default case
    let default = patterns.last().is_none_or(|p| p.starts_with('!'));
    default
}

#[cfg(test)]
#[path = "up_command_test.rs"]
mod tests;
