#!/usr/bin/env ruby
#
# category: Git commands
# help: Change directory to the git directory of the specified repository
# help:
# help: If no repository is specified, change to the git directory of the
# help: main org as specified by \e[3mOMNI_ORG\e[0m, if specified, or errors out if
# help: not specified.
# help:
# help: \033[1m\e[3mUsage\e[0m\033[1m: omni cd \e[36m[repo]\e[0m
# help:
# help:   \e[36mrepo\e[0m      The name of the repo to change directory to; this
# help:             can be in the format <org>>/<repo>, or just <repo>,
# help:             in which case the repo will be searched for in all
# help:             the organizations, trying to use \e[3mOMNI_ORG\e[0m if it is
# help:             set, and then trying all the other organizations
# help:             alphabetically.

require 'colorize'

require_relative '../lib/env'
require_relative '../lib/git'
require_relative '../lib/utils'

repo = ARGV[0]

address = repo_address?(repo)
if address
  path = "#{address.host}#{address.path.sub(/\.git$/, '')}"
  full_path = "#{OmniEnv::OMNI_GIT}/#{path}"

  unless File.directory?(full_path)
    STDERR.puts "#{"omni:".light_cyan} #{"cd command failed:".red} #{repo}: No such repository"
    exit 1
  end

  # Shell escape full_path using ruby lib
  omni_cmd(['cd', full_path])

  exit 0
end

puts "repo: #{repo}"
