use serde::Deserialize;
// Note: Serialize is auto-generated by compote::Config derive macro

/// GithubReleaseCacheConfig using compote's derive macro.
///
/// The compote::Config derive macro automatically generates:
/// - `FromConfigValue` implementation for deserialization from compote's Config
/// - `serde::Serialize` implementation for serialization
#[derive(Debug, Clone, compote::Config)]
pub struct GithubReleaseCacheConfig {
    #[compote(duration, default = "86400")]
    pub versions_expire: u64, // 1 day

    #[compote(duration, default = "7776000")]
    pub versions_retention: u64, // 90 days

    #[compote(duration, default = "604800")]
    pub cleanup_after: u64, // 1 week
}

impl GithubReleaseCacheConfig {
    const DEFAULT_VERSIONS_EXPIRE: u64 = 86400; // 1 day
    const DEFAULT_VERSIONS_RETENTION: u64 = 7776000; // 90 days
    const DEFAULT_CLEANUP_AFTER: u64 = 604800; // 1 week
}

// Note: serde::Serialize is auto-generated by compote::Config derive macro

// Manual Deserialize implementation for compatibility with existing code
impl<'de> Deserialize<'de> for GithubReleaseCacheConfig {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct Helper {
            #[serde(default = "default_versions_expire")]
            versions_expire: u64,
            #[serde(default = "default_versions_retention")]
            versions_retention: u64,
            #[serde(default = "default_cleanup_after")]
            cleanup_after: u64,
        }

        fn default_versions_expire() -> u64 { 86400 }
        fn default_versions_retention() -> u64 { 7776000 }
        fn default_cleanup_after() -> u64 { 604800 }

        let helper = Helper::deserialize(deserializer)?;
        Ok(GithubReleaseCacheConfig {
            versions_expire: helper.versions_expire,
            versions_retention: helper.versions_retention,
            cleanup_after: helper.cleanup_after,
        })
    }
}

impl Default for GithubReleaseCacheConfig {
    fn default() -> Self {
        Self {
            versions_expire: Self::DEFAULT_VERSIONS_EXPIRE,
            versions_retention: Self::DEFAULT_VERSIONS_RETENTION,
            cleanup_after: Self::DEFAULT_CLEANUP_AFTER,
        }
    }
}
