use serde::Deserialize;
// Note: Serialize is auto-generated by compote::Config derive macro

/// HomebrewCacheConfig using compote's derive macro.
///
/// The compote::Config derive macro automatically generates:
/// - `FromConfigValue` implementation for deserialization from compote's Config
/// - `serde::Serialize` implementation for serialization
#[derive(Debug, Clone, compote::Config)]
pub struct HomebrewCacheConfig {
    #[compote(duration, default = "86400")]
    pub update_expire: u64, // 1 day

    #[compote(duration, default = "86400")]
    pub tap_update_expire: u64, // 1 day

    #[compote(duration, default = "86400")]
    pub install_update_expire: u64, // 1 day

    #[compote(duration, default = "43200")]
    pub install_check_expire: u64, // 12 hours

    #[compote(duration, default = "604800")]
    pub cleanup_after: u64, // 1 week
}

impl HomebrewCacheConfig {
    const DEFAULT_UPDATE_EXPIRE: u64 = 86400; // 1 day
    const DEFAULT_TAP_UPDATE_EXPIRE: u64 = 86400; // 1 day
    const DEFAULT_INSTALL_UPDATE_EXPIRE: u64 = 86400; // 1 day
    const DEFAULT_INSTALL_CHECK_EXPIRE: u64 = 43200; // 12 hours
    const DEFAULT_CLEANUP_AFTER: u64 = 604800; // 1 week
}

// Note: serde::Serialize is auto-generated by compote::Config derive macro

// Manual Deserialize implementation for compatibility with existing code
impl<'de> Deserialize<'de> for HomebrewCacheConfig {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct Helper {
            #[serde(default = "default_update_expire")]
            update_expire: u64,
            #[serde(default = "default_tap_update_expire")]
            tap_update_expire: u64,
            #[serde(default = "default_install_update_expire")]
            install_update_expire: u64,
            #[serde(default = "default_install_check_expire")]
            install_check_expire: u64,
            #[serde(default = "default_cleanup_after")]
            cleanup_after: u64,
        }

        fn default_update_expire() -> u64 { 86400 }
        fn default_tap_update_expire() -> u64 { 86400 }
        fn default_install_update_expire() -> u64 { 86400 }
        fn default_install_check_expire() -> u64 { 43200 }
        fn default_cleanup_after() -> u64 { 604800 }

        let helper = Helper::deserialize(deserializer)?;
        Ok(HomebrewCacheConfig {
            update_expire: helper.update_expire,
            tap_update_expire: helper.tap_update_expire,
            install_update_expire: helper.install_update_expire,
            install_check_expire: helper.install_check_expire,
            cleanup_after: helper.cleanup_after,
        })
    }
}

impl Default for HomebrewCacheConfig {
    fn default() -> Self {
        Self {
            update_expire: Self::DEFAULT_UPDATE_EXPIRE,
            tap_update_expire: Self::DEFAULT_TAP_UPDATE_EXPIRE,
            install_update_expire: Self::DEFAULT_INSTALL_UPDATE_EXPIRE,
            install_check_expire: Self::DEFAULT_INSTALL_CHECK_EXPIRE,
            cleanup_after: Self::DEFAULT_CLEANUP_AFTER,
        }
    }
}
