use serde::Deserialize;
// Note: Serialize is auto-generated by compote::Config derive macro

/// MiseCacheConfig using compote's derive macro.
///
/// The compote::Config derive macro automatically generates:
/// - `FromConfigValue` implementation for deserialization from compote's Config
/// - `serde::Serialize` implementation for serialization
#[derive(Debug, Clone, compote::Config)]
pub struct MiseCacheConfig {
    #[compote(duration, default = "86400")]
    pub update_expire: u64, // 1 day

    #[compote(duration, default = "86400")]
    pub plugin_update_expire: u64, // 1 day

    #[compote(duration, default = "3600")]
    pub plugin_versions_expire: u64, // 1 hour

    #[compote(duration, default = "7776000")]
    pub plugin_versions_retention: u64, // 90 days

    #[compote(duration, default = "604800")]
    pub cleanup_after: u64, // 1 week
}

impl MiseCacheConfig {
    const DEFAULT_UPDATE_EXPIRE: u64 = 86400; // 1 day
    const DEFAULT_PLUGIN_UPDATE_EXPIRE: u64 = 86400; // 1 day
    const DEFAULT_PLUGIN_VERSIONS_EXPIRE: u64 = 3600; // 1 hour
    const DEFAULT_PLUGIN_VERSIONS_RETENTION: u64 = 7776000; // 90 days
    const DEFAULT_CLEANUP_AFTER: u64 = 604800; // 1 week
}

// Note: serde::Serialize is auto-generated by compote::Config derive macro

// Manual Deserialize implementation for compatibility with existing code
impl<'de> Deserialize<'de> for MiseCacheConfig {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct Helper {
            #[serde(default = "default_update_expire")]
            update_expire: u64,
            #[serde(default = "default_plugin_update_expire")]
            plugin_update_expire: u64,
            #[serde(default = "default_plugin_versions_expire")]
            plugin_versions_expire: u64,
            #[serde(default = "default_plugin_versions_retention")]
            plugin_versions_retention: u64,
            #[serde(default = "default_cleanup_after")]
            cleanup_after: u64,
        }

        fn default_update_expire() -> u64 { 86400 }
        fn default_plugin_update_expire() -> u64 { 86400 }
        fn default_plugin_versions_expire() -> u64 { 3600 }
        fn default_plugin_versions_retention() -> u64 { 7776000 }
        fn default_cleanup_after() -> u64 { 604800 }

        let helper = Helper::deserialize(deserializer)?;
        Ok(MiseCacheConfig {
            update_expire: helper.update_expire,
            plugin_update_expire: helper.plugin_update_expire,
            plugin_versions_expire: helper.plugin_versions_expire,
            plugin_versions_retention: helper.plugin_versions_retention,
            cleanup_after: helper.cleanup_after,
        })
    }
}

impl Default for MiseCacheConfig {
    fn default() -> Self {
        Self {
            update_expire: Self::DEFAULT_UPDATE_EXPIRE,
            plugin_update_expire: Self::DEFAULT_PLUGIN_UPDATE_EXPIRE,
            plugin_versions_expire: Self::DEFAULT_PLUGIN_VERSIONS_EXPIRE,
            plugin_versions_retention: Self::DEFAULT_PLUGIN_VERSIONS_RETENTION,
            cleanup_after: Self::DEFAULT_CLEANUP_AFTER,
        }
    }
}
