name: Auto-pull-request for cargo maintenance


on:
  # Run on push to main
  push:
    branches:
      - main
    paths:
      - .github/workflows/auto-pr-cargo-maintenance.yaml
      - Cargo.lock
      - '*.rs'
      - '**/*.rs'

  # Run weekly
  schedule:
    - cron: '0 0 * * Sun'

  # Needed so we can run it manually
  workflow_dispatch:


permissions:
  contents: read


defaults:
  run:
    shell: bash


env:
  # So cargo doesn't complain about unstable features
  RUSTC_BOOTSTRAP: 1
  # Which branch to use to make the pull request
  PR_BRANCH: auto/cargo_maintenance
  # Whether or not to enable auto-merge
  PR_AUTO_MERGE: true


jobs:
  check-pull-request:
    name: Check if the pull request exists

    runs-on: ubuntu-latest

    if: github.repository_owner == 'xaf'

    permissions:
      contents: read
      pull-requests: read

    outputs:
      pull_request_state: ${{ env.PR_STATE }}
      should_run: ${{ github.event_name != 'push' || env.PR_STATE == 'OPEN' }}

    steps:
      - name: Checkout commit
        uses: actions/checkout@v7

      - name: Check if pull request already exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          STATE=$(gh pr view "${{ env.PR_BRANCH }}" \
                    --repo "${{ github.repository }}" \
                    --json state --jq '.state' || \
                  echo "NOT FOUND")

          echo "PR_STATE=${STATE}" | tee -a "$GITHUB_ENV"

  run-cargo-maintenance:
    name: Update dependencies and run cargo fixes

    runs-on: ubuntu-latest

    needs:
      - check-pull-request

    if: needs.check-pull-request.outputs.should_run == 'true'

    outputs:
      any_update: ${{ env.UPDATES }}

    steps:
      - name: Checkout commit
        uses: actions/checkout@v7

      - name: Get rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargo-maintenance

      - name: Update cargo dependencies
        run: |
          cargo update --color=never 2>&1 \
            | tee -a cargo_update.log

      - name: Run cargo fix
        env:
          __CARGO_FIX_YOLO: 1 # So that we offer all the fixes
        run: |
          cargo fix --all-features --color always --allow-dirty

      - name: Run clippy --fix
        env:
          __CARGO_FIX_YOLO: 1 # So that we offer all the fixes
        run: |
          cargo clippy --fix --all-features --color always --allow-dirty

      - name: Run rustfmt
        run: |
          cargo fmt --verbose

      - name: Check if there is any update
        run: |
          git diff --name-only
          git diff --quiet && \
            UPDATES=false || \
            UPDATES=true
          echo "UPDATES=${UPDATES}" | tee -a "$GITHUB_ENV"

      - name: Create archive of modified files
        if: ${{ env.UPDATES == 'true' }}
        run: |
          git stash
          git diff 'stash@{0}' -z --name-only | \
            xargs -0 git archive 'stash@{0}' -o cargo-maintenance.zip --

      - name: Upload cargo-maintenance.zip artifact for use in PR
        if: ${{ env.UPDATES == 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: cargo-maintenance
          path: cargo-maintenance.zip
          retention-days: 1

      - name: Upload cargo-update log artifact for use in PR
        if: ${{ env.UPDATES == 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: cargo-updates
          path: cargo_update.log
          retention-days: 1


  create-or-update-pr:
    name: Create or update pull-request

    runs-on: ubuntu-latest

    needs:
      - check-pull-request
      - run-cargo-maintenance

    if: needs.check-pull-request.outputs.should_run == 'true' && needs.run-cargo-maintenance.outputs.any_update == 'true'

    env:
      PR_TITLE: "chore(deps): update cargo dependencies and fixes"

    steps:
      - name: Create application token
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ secrets.OMNICLI_APP_ID }}
          private-key: ${{ secrets.OMNICLI_PRIVATE_KEY }}

      - name: Checkout commit
        uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Download cargo-maintenance.zip from update job
        uses: actions/download-artifact@v8
        with:
          name: cargo-maintenance

      - name: Unzip cargo-maintenance.zip
        run: |
          unzip -o cargo-maintenance.zip -d .
          rm cargo-maintenance.zip

      - name: Download cargo-update log from update job
        uses: actions/download-artifact@v8
        with:
          name: cargo-updates

      - name: Craft commit message
        run: |
          echo "${{ env.PR_TITLE }}" | tee commit.txt
          if [[ -s cargo_update.log ]]; then
            echo | tee -a commit.txt
            cat cargo_update.log | tee -a commit.txt
          fi

      - name: Craft pull-request body
        run: |
          echo 'Updating `Cargo.lock` and applying available cargo fixes' | tee body.md
          echo | tee -a body.md
          echo "The following files have been updated:" | tee -a body.md
          echo | tee -a body.md
          git diff --name-only | while read file; do echo "- \`${file}\`"; done | tee -a body.md
          if [[ -s cargo_update.log ]]; then
            echo | tee -a body.md
            echo 'The following dependencies were updated:' | tee -a body.md
            echo | tee -a body.md
            awk 'NR > 1 && /Updating/ { \
              sub(/^v/, "", $3); \
              sub(/^v/, "", $5); \
              printf "- [`%s`](https://crates.io/crates/%s) "\
                     "([`v%s`](https://docs.rs/%s/%s/) -> "\
                     "[`v%s`](https://docs.rs/%s/%s/))\n",\
                     $2, $2, $3, $2, $3, $5, $2, $5\
              }' cargo_update.log | tee -a body.md
          fi

      - name: git commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch --force-create "${{ env.PR_BRANCH }}"
          git add --all
          git reset -- cargo_update.log
          git commit --no-verify --file=commit.txt

      - name: git push
        run: |
          git push --no-verify --force --set-upstream origin "${{ env.PR_BRANCH }}"

      - name: Create or update pull-request
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_STATE: ${{ needs.check-pull-request.outputs.pull_request_state }}
        run: |
          if [[ "$PR_STATE" != "OPEN" ]]; then
            gh pr create \
              --title "${{ env.PR_TITLE }}" \
              --body-file body.md \
              --repo "${{ github.repository }}" \
              --label dependencies \
              --label rust
          else
            gh pr edit "${{ env.PR_BRANCH }}" \
              --title "${{ env.PR_TITLE }}" \
              --body-file body.md \
              --repo "${{ github.repository }}" \
              --add-label dependencies \
              --add-label rust
          fi

      - name: Enable auto-merge
        if: ${{ env.PR_AUTO_MERGE == 'true' }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          NUM=$(gh pr view "${{ env.PR_BRANCH }}" \
                  --repo "${{ github.repository }}" \
                  --json number --jq '.number' || \
                echo "")

          if [[ -z "$NUM" ]]; then
            echo "Failed to get PR number"
            exit 1
          fi

          gh pr merge --squash --auto --body "" "$NUM"


  close-pr:
    name: Close pull-request

    runs-on: ubuntu-latest

    needs:
      - check-pull-request
      - run-cargo-maintenance

    if: needs.check-pull-request.outputs.should_run == 'true' && needs.run-cargo-maintenance.outputs.any_update == 'false' && needs.check-pull-request.outputs.pull_request_state == 'OPEN'

    env:
      PR_CLOSING_COMMENT: "Superseded. No more dependencies or fixes to apply for now."

    steps:
      - name: Create application token
        uses: actions/create-github-app-token@v3
        id: app-token
        env:
          APP_ID: ${{ secrets.OMNICLI_APP_ID }}
          PRIVATE_KEY: ${{ secrets.OMNICLI_PRIVATE_KEY }}
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ env.PRIVATE_KEY }}

      - name: Close pull-request
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr close "${{ env.PR_BRANCH }}" \
            --comment "${{ env.PR_CLOSING_COMMENT }}" \
            --delete-branch
