name: Build and test release
run-name: Build and test ${{ inputs.git_sha }} for ${{ inputs.release_version }}


on:
  # Allows to run this workflow by being called from another workflow
  workflow_call:
    inputs:
      git_sha:
        description: The git sha to build the release for
        type: string
      release_version:
        description: The release version to use for the build
        type: string
      sign:
        description: Whether to sign the artifact
        type: boolean
        default: true
    outputs:
      release_version:
        description: The release version that was used for the build
        value: ${{ inputs.release_version }}

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git_sha:
        description: The git sha to build the release for
        type: string
      release_version:
        description: The release version to use for the build
        type: string
      sign:
        description: Whether to sign the artifact
        type: boolean
        default: true


concurrency:
  group: ${{ github.workflow }}-${{ inputs.git_sha }}
  cancel-in-progress: false


jobs:
  build-and-test-binaries:
    name: Build and test binary for ${{ matrix.suffix }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            suffix: arm64-linux
            run_tests: false
          - target: aarch64-apple-darwin
            os: macos-latest
            suffix: arm64-darwin
            run_tests: false
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            suffix: x86_64-linux
            run_tests: true
            extra_test_containers: '["archlinux:base-devel", "fedora:latest"]'
          - target: x86_64-apple-darwin
            os: macos-latest
            suffix: x86_64-darwin
            run_tests: true

    uses: ./.github/workflows/build-and-test-target.yaml
    with:
      git_sha: ${{ inputs.git_sha || github.sha }}
      release_version: ${{ inputs.release_version }}
      target: ${{ matrix.target }}
      os: ${{ matrix.os }}
      suffix: ${{ matrix.suffix }}
      run_tests: ${{ matrix.run_tests }}
      extra_test_containers: ${{ matrix.extra_test_containers }}
      sign: ${{ inputs.sign }}
