name: "Pull Request Labeler"


on:
  - pull_request_target



jobs:
  triage:
    name: Triage

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Run labeler
      uses: actions/labeler@v5
      with:
        configuration-path: .github/labeler.yaml
        sync-labels: true
        dot: true
