name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    name: Create new github release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Prepare changelog for the release
        run: |
          git fetch --append --tags --unshallow --force
          tags=($(git tag --list | tail -n2))
          echo "RELEASE_CHANGELOG<<EOF" | tee -a "$GITHUB_ENV"
          git log --pretty=format:"- %s (%an)" "${tags[0]}".."${tags[1]}" | tee -a "$GITHUB_ENV"
          echo | tee -a "$GITHUB_ENV"
          echo "EOF" | tee -a "$GITHUB_ENV"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          skipIfReleaseExists: true
          makeLatest: true
          body: ${{ env.RELEASE_CHANGELOG }}


  publish-crate:
    name: Publish crate

    needs:
      - create-release

    outputs:
      release_version: ${{ env.RELEASE_VERSION }}

    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Get release version
        run: |
          RELEASE=$(git describe --tags --always)
          RELEASE_VERSION=${RELEASE##v}
          echo "RELEASE_VERSION=${RELEASE_VERSION}" | tee -a "$GITHUB_ENV"

      - name: Override Cargo.toml and Cargo.lock version
        run: |
          sed -i 's/^version = "0\.0\.0-git"$/version = "'"${RELEASE_VERSION}"'"/' Cargo.toml
          sed -i 's/^version = "0\.0\.0-git"$/version = "'"${RELEASE_VERSION}"'"/' Cargo.lock

      - name: Publish crate
        env:
          OMNI_RELEASE_VERSION=${{ env.RELEASE_VERSION }}
        run: |
          # We use --allow-dirty since we override the version key
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --allow-dirty

      - name: Reset Cargo.toml and Cargo.lock
        run: |
          git checkout Cargo.toml
          git checkout Cargo.lock


  upload-assets:
    name: Build new binary for ${{ matrix.suffix }}

    needs:
      - create-release
      - publish-crate

    env:
      RELEASE_VERSION: ${{ needs.publish-crate.outputs.release_version }}

    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            suffix: arm64-linux
          - target: aarch64-apple-darwin
            os: macos-latest
            suffix: arm64-darwin
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            suffix: x86_64-linux
          - target: x86_64-apple-darwin
            os: macos-latest
            suffix: x86_64-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Build and upload binary
        uses: taiki-e/upload-rust-binary-action@v1
        env:
          OMNI_RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        with:
          bin: omni
          archive: omni-${{ env.RELEASE_VERSION }}-${{ matrix.suffix }}
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          checksum: sha256

  update-brew:
    name: Trigger brew formula update

    needs:
      - upload-assets

    runs-on: ubuntu-latest

    steps:
      - name: Send repository dispatch with update-formulae event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
          repository: XaF/homebrew-omni
          event-type: update-formulae
