name: Continuous testing

on:
  push:
    branches:
      - rust
  pull_request:
    branches:
      - rust

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
    - name: Checkout current commit
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose


  auto-merge:
    name: Auto-merge Dependabot pull-requests
    runs-on: "ubuntu-latest"

    if: github.actor == 'dependabot[bot]'

    needs:
      - tests

    permissions:
      contents: none

    steps:
    - name: Automerge if Dependabot
      uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        target: minor
        command: 'squash and merge'
        github-token: ${{ secrets.AUTOMERGE_TOKEN }}
