name: Continuous testing


on:
  # Runs on a push
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/release.yaml
      - .github/workflows/website.yaml
      - README.md
      - "website/**"

  # Runs on a pull request
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/workflows/release.yaml
      - .github/workflows/website.yaml
      - README.md
      - "website/**"

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  prepare-release-version:
    name: Prepare build version

    runs-on: ubuntu-latest

    outputs:
      release_version: ${{ env.RELEASE_VERSION }}

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Get release version
        run: |
          git fetch --append --tags --unshallow --force
          RELEASE_VERSION=$(git describe --tags --broken --dirty --match v* 2>/dev/null || true)
          [ -z "$RELEASE_VERSION" ] && \
            RELEASE_VERSION=0.0.0-g$(git describe --tags --always --broken --dirty --match v*)
          RELEASE_VERSION=${RELEASE_VERSION##v}
          echo "RELEASE_VERSION=${RELEASE_VERSION}" | tee -a "$GITHUB_ENV"


  build-and-test-binaries:
    name: Build and test binaries

    needs:
      - prepare-release-version

    uses: ./.github/workflows/build.yaml
    with:
      git_sha: ${{ github.sha }}
      release_version: ${{ needs.prepare-release-version.outputs.release_version }}


  auto-merge:
    name: Auto-merge Dependabot pull-requests

    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'

    needs:
      - build-and-test-binaries

    permissions:
      contents: none

    steps:
    - name: Automerge if Dependabot
      uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        target: minor
        command: 'squash and merge'
        github-token: ${{ secrets.AUTOMERGE_TOKEN }}
