name: Continuous testing

on:
  # Runs on a push
  push:
    branches:
      - main

  # Runs on a pull request
  pull_request:
    branches:
      - main

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check-changed-files:
    name: Check changed files
    runs-on: ubuntu-latest

    outputs:
      run-tests: ${{ steps.changed-files.outputs.any_modified }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed source files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files_ignore: |
            README.md
            website

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo "$file was modified"
          done


  run-tests:
    name: Run tests

    needs:
      - check-changed-files
    if: needs.check-changed-files.outputs.run-tests == 'true'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout current commit
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose


  auto-merge:
    name: Auto-merge Dependabot pull-requests
    runs-on: "ubuntu-latest"

    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'

    needs:
      - run-tests

    permissions:
      contents: none

    steps:
    - name: Automerge if Dependabot
      uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        target: minor
        command: 'squash and merge'
        github-token: ${{ secrets.AUTOMERGE_TOKEN }}
